version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"

    ports:
      - "1433:1433"

    volumes:
      # Bind mount to local Windows folders
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./backup:/var/opt/mssql/backup

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G

    networks:
      - mssql_net

networks:
  mssql_net:
    driver: bridge