version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: MySQL-Official
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - E:/docker-hub/MySQL/Data:/var/lib/mysql
