version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - E:/docker-hub/Redis/Data:/data
    command: redis-server --appendonly yes